displayName=BossReadinessScore
author=Oyama
support=https://github.com/ItMeansBigMountain/BossReadinessScore
description=BossReadinessScore RuneLite plugin.
tags=bossreadinessscore,runelite,osrs
plugins=com.itmeansbigmountain.bossreadinessscore.BossReadinessScorePlugin
